"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StateProvider from "@/components/state-provider/StateProvider";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/common/theme-provider";
import Header from "@/components/header/header";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// // {...inter.className}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StateProvider>
      <SessionProvider >
      <html
        lang="en"
      >
        <body >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header/>
            {/* <div className="mt-16"> */}

            {children}
            {/* </div> */}
          </ThemeProvider>
        </body>
      </html>
       </SessionProvider>
    </StateProvider>
  );
}
