import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StateProvider from "@/components/state-provider/StateProvider";
import SideBar from "@/components/sidebar/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// {...inter.className}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StateProvider>
      <html
        lang="en"
        className="h-full w-full bg-white flex items-center justify-center"
      >
        <body className="bg-gray-600 w-full min-h-full items-center justify-center ">
          <SideBar />
          {children}
        </body>
      </html>
    </StateProvider>
  );
}
