import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StateProvider from "@/components/state-provider/StateProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StateProvider>
      <html lang="en" className="h-full bg-white flex items-center justify-center">
        {/*  {...inter.className} */}
        <body className="h-3/4 w-3/4 bg-gray-600 items-center justify-center ">{children}</body>
      </html>
    </StateProvider>
  );
}
